### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.randint(1,51,10)

media = np.mean(arr)

desvPad = np.std(arr)

print(arr)
print(media)
print(desvPad)

[ 5 49 36 23 42 13 50 30 14 26]
28.8
14.702380759591286


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.54172473 0.33930396 0.64322282 0.44100439 0.83858445 0.60325017
 0.30349679 0.58770198 0.57321583 0.61338963]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

matriz = np.random.randint(low=0, high=10, size=(3, 3, 3))

for matriz2d in matriz:
    print("Matriz 2D:")
    print(matriz2d)
    for linha in matriz2d:
        print("Valor máximo da linha:", max(linha))


Matriz 2D:
[[7 7 0]
 [3 4 2]
 [3 0 2]]
Valor máximo da linha: 7
Valor máximo da linha: 4
Valor máximo da linha: 3
Matriz 2D:
[[4 5 3]
 [2 2 4]
 [1 4 0]]
Valor máximo da linha: 5
Valor máximo da linha: 4
Valor máximo da linha: 4
Matriz 2D:
[[8 0 4]
 [5 9 6]
 [5 7 1]]
Valor máximo da linha: 8
Valor máximo da linha: 9
Valor máximo da linha: 7


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

matriz = np.random.rand(5, 5)

media = np.mean(matriz, axis=1)

matriz_media_subtraida = matriz - media.reshape(-1, 1)

print(matriz_media_subtraida)


[[-0.14592494 -0.24760991  0.38285565 -0.35057771  0.36125691]
 [ 0.28264803 -0.29820911  0.54780696 -0.18818194 -0.34406394]
 [-0.15975045  0.24597624  0.19169721 -0.10547744 -0.17244555]
 [-0.09275364  0.37722962 -0.2409868  -0.1154154   0.07192623]
 [-0.06942524  0.07106845 -0.02123405 -0.04377515  0.063366  ]] [[0.48972916]
 [0.39138741]
 [0.59843501]
 [0.52313476]
 [0.41032464]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

matriz = np.random.rand(4, 4)

diagonal_principal = np.diag(matriz)
diagonal_secundaria = np.diag(np.fliplr(matriz))

media_diagonal_principal = np.mean(diagonal_principal)
desvio_padrao_diagonal_principal = np.std(diagonal_principal)

media_diagonal_secundaria = np.mean(diagonal_secundaria)
desvio_padrao_diagonal_secundaria = np.std(diagonal_secundaria)

print("Diagonal principal: média = {:.2f}, desvio padrão = {:.2f}".format(media_diagonal_principal, desvio_padrao_diagonal_principal))
print("Diagonal secundária: média = {:.2f}, desvio padrão = {:.2f}".format(media_diagonal_secundaria, desvio_padrao_diagonal_secundaria))


Diagonal principal: média = 0.44, desvio padrão = 0.30
Diagonal secundária: média = 0.72, desvio padrão = 0.22
